image: maven:latest

stages:
  - test

maven:
  stage: test
  cache:
    paths:
      - .m2/repository
  script:
    - mvn --version
    - mvn test
    - mvn verify # runs OWASP dependency-check
  artifacts:
    paths:
      - target/dependency-check-report.html

# included in test stage
include:
  - template: Jobs/SAST.gitlab-ci.yml
