image: maven:latest

stages:
  - test

test:
  stage: test
  script:
    - mvn --version
    - mvn test
    - mvn verify # runs OWASP dependency-check
  artifacts:
    paths:
      - target/dependency-check-report.html

# test stage
include:
  - template: Jobs/SAST.gitlab-ci.yml
